//
//  place.swift
//  wonderfulbatam
//
//  Created by Ihwan ID on 30/04/20.
//  Copyright © 2020 Ihwan ID. All rights reserved.
//

import UIKit
 
struct Place {
    let photo: UIImage
    let name: String
    let description: String
    let latitude: Double
    let longitude: Double
    
}

var places: [Place] = [
    Place(photo: UIImage(named: "barelang")!, name: "Jembatan Barelang", description: "Jembatan Barelang adalah ikon wisata Batam. Anda dianggap belum ke Batam sebelum menyinggahi jembatan yang satu ini. Sejatinya, jembatan ini bernama Tengku Fisabilillah, namun belakangan masyarakat lebih senang menyebutnya dengan Jembatan Barelang ketimbang nama aslinya. Memiliki panjang 644 meter dengan bentang jembatan 530 meter, Jembatan Barelang merupakan satu dari enam jembatan yang dibangun di era BJ Habibie memimpin Otorita Batam, untuk menghubungkan Batam dengan Rempang, Galang dan beberapa pulau lainnya seperti Pulau Nipah, Setoko serta Pulau Galang Baru. Dibangun menggunakan system cable stay, jembatan ini elok dipandang dari sudut mana pun Apalagi kalau dilihat dari udara, kemegahannya makin terlihat nyata.", latitude:
    0.9813378194785338, longitude: 104.04177855111413),
    Place(photo: UIImage(named: "abang")!, name: "Pulau Abang", description: "Inilah destinasi wisata maritim terkemuka di Batam. Namanya Pulau Abang, sebuah pulau kecil yang berada di sisi paling Selatan Pulau Batam dan merupakan bagian dari Kecamatan Galang. Sebagai kawasan wisata laut yang sedang dikembangkan oleh pemerintah Kota Batam, Pulau Abang adalah surga bagi Anda penyuka diving, snorkeling, island hopping, memancing dan berbagai aktifitas olahraga air lainnya. Pulau ini dikelilingi oleh beberapa pulau kecil seperti pulau Petong, Pulau Dedap, Pulau Hantu. Pulau Pengerlap, Pulau Kelapa dan Pulau Abang Besar. Hampir setiap titik perairannya, ditumbuhi rupa-rupa terumbu karang yang masih terjaga kealamiannya.", latitude: 0.5836500287296269, longitude:  104.1922416666057),
    Place(photo: UIImage(named: "putri")!, name: "Pulau Putri", description: "Letak administratif Kepri yang berbatasan langsung dengan dua negara tetangga seperti Singapura dan Malaysia, lanjutnya, menjadikan Provinsi Kepri sebagai salah satu provinsi yang memiliki 22 pulau terdepan seperti tercantum dalam Keppres Nomor 6 Tahun 2017 tentang Penetapan Pulau-Pulau Kecil Terluar. 'Salah satu pulau terdepan di Kepri, ya berada di Kota Batam, yaitu Pulau Putri di Kecamatan Nongsa,' katanya. Awalnya Pulau Putri, lanjut Ismail, terdiri dari satu kesatuan pulau. Karena abrasi pantai, menyebabkan Pulau Putri terpisah menjadi tiga bagian yang terlihat pada kondisi air pasang dan akan kembali tampak menyatu menjadi satu kesatuan saat air laut surut. 'Mengingat status Pulau Putri sebagai salah satu pulau terluar, maka sangat penting untuk mempertahankan keberadaannya demi menjaga kedaulatan NKRI. Oleh sebab itu Pulau Putri menjadi perhatian khusus pemerintah, baik di pusat maupun daerah,' ujar Ismail mengakhiri.", latitude: 1.202451 , longitude: 104.076970),
    Place(photo: UIImage(named: "ranoh")!, name: "Pulau Ranoh", description: "Jika Anda berkunjung ke Pulau Batam, jangan pernah lewatkan wisata alam yang terbilang cukup baru ini, Pulau Ranoh namanya. Banyak wahana olahraga air yang disediakan di sini, sehingga tak hanya dapat bermain air sepuasnya, Anda juga dapat mempercantik galeri instagram. Beberapa kumpulan foto ini dapat memperlihatkan cantiknya Pulau Ranoh, dan patut dikunjungi. Pulau Ranoh adalah satu dari banyak obyek wisata dari gugusan Pulau Abang, Batam, Kepulauan Riau. Pulau Ranoh memiliki pasir pantai yang menimbul pada pemukaannya sehingga membentuk sebuah semenanjung kecil ke laut dalam dengan air laut yang Jernih dan tenang. Ada banyak fasilitas yang bisa didapatkan di area glamping. Mulai dari api unggun, barbeque set, hingga mini bar. Selain itu, pelancong juga akan mendapat paket makam malam di Pulau Ranoh. Pada area pantai juga terdapat pepohonan rindang. Kesan mewah tergambar juga dengan adanya fasilitas hammock dan bean bag yang tersedia di area pantai. Serunya, bersantai di sana sambil menikmati keindahan alam yang ada di Pulau Ranoh", latitude: 0.0, longitude: 0.0),
    Place(photo: UIImage(named: "tebing")!, name: "Tebing Langit", description: "Tebing langit merupakan destinasi wisata baru, yang terletak di Sekupang, Kota Batam, Provinsi Kepulauan Riau, yang kini menjadi perbincangan hangat bagi kaum Millenial di Kota Batam. Keunikan yang disajikan oleh destinasi wisata ini, berbeda jauh dengan destinasi wisata lainnya di Kota Batam yang selalu identik dengan pemandangan pantai. Ditebing langit selain kita dapat menikmati keindahan pantai, namun spot-spot foto di lokasi destinasi wisata tersebut, sangat menarik untuk para Millenial yang ingin mengabadikan foto-foto selfi mereka dengan spot-spot yang menarik. Ada beberapa nama lokasi spot foto yang menarik di Tebing langit, diantaranya pintu langit, lorong langit, bintang harapan, kampung indian, rumah rabbit, dan beberapa tempat lainnya yang sangat menarik dijadikan background foto. Untuk menuju kelokasi tersebut, kalian para pemuja keindahan harus melewati, beberapa anak tangga untuk sampai di puncak. Namun kelelahan untuk tiba puncak, akan terbayarkan setelah kita tiba dipuncak karena suguhan pemandangan, Tebing langit yang begitu menawan. Dari atas Tebing langit, kita juga dapat menikmati keindahan matahari saat terbenam di sore hari.", latitude: 0.0, longitude: 0.0),
    Place(photo: UIImage(named: "montigo")!, name: "Montigo", description: "Terletak di Nongsa di pantai timur laut Batam, Montigo Resort Nongsa bisa dicapai dalam 5 menit berkendara dari Nongsapura Ferry Terminal, 30 menit berkendara dari Bandara Internasional Hang Nadim, dan 45 menit berkendara dari Nagoya City Centre. Layanan penjemputan gratis dari Nongsapura ke resor ditawarkan. Menawarkan pemandangan panorama laut, semua unit minimalis modern dilengkapi dengan perabotan kayu gelap yang elegan, TV layar datar, dan iPod dock. Masing-masing vila memiliki teras atap di mana Anda dapat menikmati pemandangan matahari terbenam di Laut China Selatan. Dapur lengkap dan kamar mandi dalam dengan fasilitas lengkap termasuk dalam semua unit. Beberapa lapangan golf kelas dunia berada dalam jarak sekitar 3 km dari resor ini. Anda dapat menikmati pijat relaksasi di spa, bermain tenis, atau menggunakan fasilitas barbekyu. Layanan penukaran uang dan penyewaan kendaraan tersedia di meja layanan wisata. Terdapat juga layanan antar-jemput bandara dengan biaya tambahan. TADD’s dikelilingi oleh tanaman hijau asri dan menampilkan pemandangan laut, serta menawarkan hidangan khas Asia dan Barat. Menawarkan pemandangan kolam renang dan laut serta lounge permainan, Tiigo Beach Club menyediakan berbagai pilihan minuman bar dan spesialisasi Barat. Anda juga dapat menikmati sepotong kue dan secangkir kopi di Café Montigo, atau menikmati makanan laut segar di Pantai. Atau, Anda juga dapat bersantap dalam kenyamanan vila Anda.", latitude: 0.0, longitude: 0.0),
    Place(photo: UIImage(named: "coral")!, name: "Kepri Coral", description: "Baru baru ini kota Batam disuguhkan dengan destinasi wisata baru yang hangat di bahas para wisatawan Asing dan Lokal , Kepri Coral namanya sebuah destinasi baru yang terdiri dari Kolam Renang dan Akuarium bawah laut yang menakjubkan, beberapa orang menyebutnya Kepri Coral Island, Sebahagian menyebutnya Kepri Coral Resort dan Banyak lagi, anda bisa melihat bawah laut pulau Pengalap dari dalam Akuarium besar disana, hmmmm seperti apa kira kira keseruannya ya?. Pemandangan bawah laut di Kepri Coral bisa anda nikmati tanpa harus berenang, cukup masuk kedalam Akuarium untuk bisa melihat ikan dan terumbu karang di luar akuarium Kepri Coral Batam, tentu destinasi wisata seperti ini masih asing di Kota Batam karena Kepri Coral merupakan yang pertama di kembangkan di Batam kepulauan Riau. Banyak aktivitas lain di Kepri Coral yang Bisa anda nikmati selai Akuarium Bawah laut raksasa ini, anda bisa bermain Zet ski, Perahu Cano, Pantai atau sekedar bermain di Pantai. Sepeda Air dan tentusaja Kolam Renang juga sudah tersedia dini", latitude: 0.0, longitude: 0.0)
]

